-- 도서 테이블 생성
CREATE TABLE IF NOT EXISTS BOOK (
    BOOK_ID VARCHAR(20) PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(100),
    PUBLISHER VARCHAR(100),
    PRICE INT,
    PAGE_COUNT INT,
    DESCRIPTION TEXT,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETE_YN CHAR(1) DEFAULT 'N'
);

-- IDS 테이블 생성 (ID Generator 용)
CREATE TABLE IF NOT EXISTS IDS (
    TABLE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_ID BIGINT NOT NULL
);

-- ID Generator 초기값 설정
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('BOOK_ID', 1)
ON CONFLICT (TABLE_NAME) DO NOTHING;

-- 초기 데이터 삽입
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHER, PRICE, PAGE_COUNT, DESCRIPTION, DELETE_YN) 
VALUES ('BOOK_000001', '자바 프로그래밍', '홍길동', '기술서적', 35000, 500, '자바 언어를 배우는 책', 'N')
ON CONFLICT (BOOK_ID) DO NOTHING;

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHER, PRICE, PAGE_COUNT, DESCRIPTION, DELETE_YN) 
VALUES ('BOOK_000002', '스프링 프레임워크', '김철수', '개발책', 42000, 600, '스프링 프레임워크를 배우는 책', 'N')
ON CONFLICT (BOOK_ID) DO NOTHING;

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, PUBLISHER, PRICE, PAGE_COUNT, DESCRIPTION, DELETE_YN) 
VALUES ('BOOK_000003', '마이바티스 마스터', '이영희', 'DB 출판', 38000, 450, '마이바티스 ORM 을 배우는 책', 'N')
ON CONFLICT (BOOK_ID) DO NOTHING;
