CREATE TABLE IF NOT EXISTS BOOK (
    BOOK_ID VARCHAR(20) PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    PUBLISHER VARCHAR(100),
    PRICE INT,
    PUBLISHED_DATE DATE,
    DESCRIPTION TEXT,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETE_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS IDS (
    TABLE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_ID BIGINT NOT NULL
);

INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('BOOK_ID', 1)
ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
